language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
install: true
script:
  -  mvn clean install
after_success:
  - mvn test jacoco:report coveralls:report

# only build master on direct commit to it
branches:
  only:
  - master
